CREATE TABLE wp_cities(
  id INT UNSIGNED PRIMARY KEY,
  name VARCHAR(128),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  udpated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  country_id INT UNSIGNED,

  FOREIGN KEY(country_id) REFERENCES wp_countries(id)
); 